Feature/46 2/pro/present exam problem be
DA-sc21/test-helper pull request #267
Opened 2021-11-27 07:45 UTC by WooNaYoung22

@leeshyeon 
시험 문제 출제 & 시험 문제 수정 rest api 입니다 !

[실행방법]
1. 문제 출제 (생성)
![image](https://user-images.githubusercontent.com/55876368/143672965-098deed1-1295-4ece-b6e5-7da73092444f.png)

2. 문제 수정
![image](https://user-images.githubusercontent.com/55876368/143672980-96d2c126-8863-445f-b134-e002be16c531.png)

2021-11-27 07:56 UTC, SongZzi approved these changes
수고하셨습니다!

2021-11-27 08:33 UTC, leeshyeon approved these changes
수고하셨습니다!

2021-11-27 17:30 UTC, KoYeJoon approved these changes
수고하셨습니다 :)

2021-11-28 02:52 UTC, jmchoi1225 requested changes
수고하셨습니다!

- Controller에서 @IsProfessor 대신 @AccessTestByProfessor가 맞는 것 같습니다
  - @IsProfessor : 교수인지 확인
  - @AccessTestByProfessor : 해당 교수가 testId에 해당하는 test에 접근 권한이 있는지
- ProblemRepository.findByTestIdAndProblemNum에서 해당 problem이 없으면 에러가 발생합니다. return값을 Problem 대신 Optional<Problem>을 하는 것을 추천합니다.
- 하나의 test안에 problemNum가 겹치는 경우가 발생할 것 같습니다... 이에 대한 처리가 필요할 것 같습니다.

2021-11-29 06:55 UTC, WooNaYoung22 reviewed
@jmchoi1225 
피드백 감사함다 👍👍
annotation 변경하구 & 문제를 찾을 수 없는 경우 & 이미 존재하는 problemNum 문제 생성하려는 경우
예외처리해두었습니다 !

2021-11-29 09:51 UTC, jmchoi1225 approved these changes
수고하셨습니다!

2021-11-29 09:51 UTC, merged