Feature/34 2/pro ass/signup be
DA-sc21/test-helper pull request #298
Opened 2021-12-02 09:44 UTC by WooNaYoung22

회원가입 내부 로직이 조금 변경되었고, 비밀번호 찾기를 추가하였습니다!
자세한 사항은 https://www.notion.so/e3e7f51681ed42409ee5b109178c8b5f?v=fb3a4aa6daf449e2bacfc6eaf333b46b&p=33e514f736524b1e81fb4862777695eb
참고부탁드려요~!

2021-12-02 09:52 UTC, KoYeJoon approved these changes
수고하셨습니다 :)

2021-12-02 09:57 UTC, jmchoi1225 requested changes
수고하셨습니다!

- AccountService.signUp()에서 PortalAccount가 없는 경우, signUp되지 않도록 막아야 할 것 같습니다.
- password 변경에 대한 보안이 더 필요할 것 같습니다.

2021-12-02 10:01 UTC, leeshyeon approved these changes
수고하셨습니다!

2021-12-02 15:54 UTC, SongZzi approved these changes
수고하셨습니다!!
추후 회원가입 부분 참고해서 수정해보겠습니다👍

2021-12-02 18:59 UTC, WooNaYoung22 reviewed
수정완료했습니다 :)
@jmchoi1225 approve 부탁드립니다 ~!
프론트 회원가입 or 임시 비밀번호 발급 or 마이페이지 비밀번호 변경 구현하시는 분
notion 참고 부탁드립니다 :)

2021-12-03 00:35 UTC, jmchoi1225 approved these changes
수고하셨습니다!

2021-12-04 05:16 UTC, merged