Feature/48 2/pro/answer sheet be
DA-sc21/test-helper pull request #314
Opened 2021-12-03 10:18 UTC by WooNaYoung22

예시 답안 등록 및 조회 구현입니다 @leeshyeon 

실행방법은
https://www.notion.so/e3e7f51681ed42409ee5b109178c8b5f?v=fb3a4aa6daf449e2bacfc6eaf333b46b&p=cd6391910f284961ab23681f0883aa20
참고 부탁드려요 :)

2021-12-03 10:59 UTC, jmchoi1225 approved these changes
수고하셨습니다!

2021-12-03 11:03 UTC, jmchoi1225 requested changes
수고하셨습니다!

- GET에서 file를 다운로드할 수 있도록 file path가 아닌 presigned url을 반환하는 것이 좋을 것 같습니다!

2021-12-03 12:43 UTC, WooNaYoung22 reviewed
수정완료했습니다 ...!
@jmchoi1225 승인 부탁드려요 ~!
@leeshyeon 답안 삭제 api를 추가했습니다
notion 참고 부탁드려요 :)

2021-12-03 16:01 UTC, leeshyeon approved these changes
수고하셨습니다!

2021-12-03 17:09 UTC, SongZzi approved these changes
수고하셨습니다!!

2021-12-03 18:46 UTC, KoYeJoon approved these changes
수고하셨습니다 :)

2021-12-04 04:10 UTC, jmchoi1225 approved these changes
수고하셨습니다!

2021-12-04 04:18 UTC, merged