Feature/31 1/admin/login fe
DA-sc21/test-helper pull request #338
Opened 2021-12-08 09:15 UTC by KoYeJoon

🧸branch
- dev ← feature

📌 기능
- 관리자 로그인 구현 (sessionStorage 사용)
![image](https://user-images.githubusercontent.com/55876348/145181501-a83519af-98de-47cf-bf99-3482cba8acf6.png)

✔️ 확인해야 할 사항
- feature/32-1에서 관리자 로그인 관련 route 추가해주었습니다 !

✏️ 추후 변경될 수 있는 사항
- X

2021-12-09 14:51 UTC, SongZzi approved these changes
수고많으셨습니다!!

2021-12-10 05:49 UTC, WooNaYoung22 approved these changes
수고하셨습니다 ~!

2021-12-10 08:13 UTC, jmchoi1225 requested changes
수고하셨습니다!

- res.status==200일 때 서버에서 return하는 에러 메세지를 보여주는 게 나을 것 같습니다.

2021-12-10 08:41 UTC, leeshyeon approved these changes
수고하셨습니다!

2021-12-10 11:16 UTC, jmchoi1225 approved these changes

2021-12-10 14:10 UTC, merged