Feature/32 1/admin/course list fe
DA-sc21/test-helper pull request #340
Opened 2021-12-08 09:24 UTC by KoYeJoon

🧸branch
- dev ← feature

📌 기능
- 관리자 수업 조회 구현
- 관리자 로그인/ 수업 조회 route 추가
- UI는 추천 받습니다 ㅜ_ㅜ
![image](https://user-images.githubusercontent.com/55876348/145182792-ebb83549-c62a-4fe7-9bd6-6425c1150a99.png)
![image](https://user-images.githubusercontent.com/55876348/145182809-7c612666-1ee4-465f-a0f5-3b49dc5dbefe.png)

✔️ 확인해야 할 사항
- feature/33-1/에서 수업 등록 관련 기능이 구현될 예정입니다.

✏️ 추후 변경될 수 있는 사항
- 좋은 UI 아이디어가 떠오르면 추가될 수 있습니다.

2021-12-09 14:52 UTC, SongZzi approved these changes
수고하셨습니다!
같이 ui 고민해봅시다아,,😂

2021-12-10 05:50 UTC, WooNaYoung22 approved these changes
수고하셨습니다 ~!!

2021-12-10 08:14 UTC, jmchoi1225 requested changes
수고하셨습니다!

- ExamineeService에서 주석처리한 거 다시 돌려주세요!

2021-12-10 08:41 UTC, leeshyeon approved these changes
수고하셨습니다!

2021-12-10 10:25 UTC, KoYeJoon commented
> 수고하셨습니다!
> 
> * ExamineeService에서 주석처리한 거 다시 돌려주세요!

@jmchoi1225  주석 처리한거 돌렸습니다 ! 확인 부탁드립니다 !! :)

2021-12-10 11:17 UTC, jmchoi1225 approved these changes

2021-12-10 14:12 UTC, merged