Feature/3 1/stu/test student waiting
DA-sc21/test-helper pull request #94
Opened 2021-11-01 15:33 UTC by leeshyeon

대학생 시험 대기 화면 대장정

이슈, 캡쳐 등 상세 사항은 아래 노션에 적었습니다~!

https://www.notion.so/3-1-FE-8d48d389c473431d9e4da7b1b70254e0

2021-11-01 15:49 UTC, SongZzi approved these changes
시험 대기화면 대장정.!!
수고넘많으셨습니당!👍👍

2021-11-01 15:57 UTC, KoYeJoon approved these changes
시험대기화면 오늘 데모보는데 눈물핑,,,,수고하셨습니당 🧸 이제 나영이랑 열심히 서버 분리되는 부분에 대해서,, 해보겠습니닿ㅎㅎ

2021-11-02 06:58 UTC, WooNaYoung22 approved these changes
진짜 대장정.... 완전 수고하셨습니다!!! 👍👍
맞아용....ㅎㅎㅎ연결하는법 얼른 해봐야겠네여ㅎㅎㅎ

2021-11-02 07:15 UTC, jmchoi1225 requested changes
수고하셨습니다!
- baseUrl인 경우, 여러 군데에서 여러번 선언하는 것 보다 한 파일에 저장하는 것이 좋을 것 같아요
  - 나중에 baseUrl값이 변경되면 지금은 선언하는 곳 마다 변경해야 하는데 만약에 바꾸면 그 파일 한개만 수정해도 되요
- /s3-upload-url, /s3-upload-url...의 형식으로 하고 path를 frontend에서 해주는 형식이 위험할 것 같아요.
  - ex) 해당 url로 학생 인증, 시험 답안지를 아무나 업로드할 수 있게 됨 (BE 단에서 권한을 따로 분리하려면 path parsing???
  - @WooNaYoung22 @leeshyeon  추후 논의 필요할 것 같아요

2021-11-03 16:38 UTC, WooNaYoung22 reviewed
@jmchoi1225 
네네! 내일 실습시간에 이 부분 논의해보면 좋을거같아요~

2021-11-04 11:36 UTC, merged