Feature/11 1/pro/verification list
DA-sc21/test-helper pull request #95
Opened 2021-11-01 15:36 UTC by leeshyeon

교수/조교 시험 감독 화면
- 감독 화면 ui
- 1차 본인인증 결과 조회 
- 2차 본인인증 수행
- 학생 정렬
- 전체 학생 한눈에 보기

상세 사항은 아래 노션 참고해주세요~!
https://www.notion.so/fb6a09e65fbd45f9a65759933f5e04a4

2021-11-01 15:54 UTC, SongZzi approved these changes
조만간 kinesis부분도 합쳐서 올리겠습니당👍
수고하셨습니다 !!

2021-11-01 16:07 UTC, KoYeJoon reviewed
근데 지금 언니가 pull request할 때 github action 작동안했죠..? github action에 react 관련 코드가 없어서 작동안했나,,뭔가 이상한게 제가 수정을 해야할 것 같네요 ㅎㅎ 😂

2021-11-02 07:01 UTC, WooNaYoung22 approved these changes
화면 넘 이쁘네요ㅎㅎㅎ 수고하셨습니다 !!👍

2021-11-02 07:18 UTC, jmchoi1225 requested changes
수고하셨습니다!

baseUrl인 경우, 여러 군데에서 여러번 선언하는 것 보다 한 파일에 저장하는 것이 좋을 것 같아요
나중에 baseUrl값이 변경되면 지금은 선언하는 곳 마다 변경해야 하는데 만약에 바꾸면 그 파일 한개만 수정해도 되요
/s3-upload-url, /s3-upload-url...의 형식으로 하고 path를 frontend에서 해주는 형식이 위험할 것 같아요.
ex) 해당 url로 학생 인증, 시험 답안지를 아무나 업로드할 수 있게 됨 (BE 단에서 권한을 따로 분리하려면 path parsing???
@WooNaYoung22 @leeshyeon 추후 논의 필요할 것 같아요

2021-11-04 11:36 UTC, merged